<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>NeoTasks.Service</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NeoTasks.Domain/NeoTasks.Domain.csproj" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.0" />
  </ItemGroup>
</Project>
