<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12"><PrivateAssets>all</PrivateAssets></PackageReference>
    <ProjectReference Include="../NeoTasks.Domain/NeoTasks.Domain.csproj" />
    <ProjectReference Include="../NeoTasks.Data/NeoTasks.Data.csproj" />
    <ProjectReference Include="../NeoTasks.Service/NeoTasks.Service.csproj" />
  </ItemGroup>
</Project>
